from django.conf.urls import url, include
from rest_framework_mongoengine import routers

from . import views
from . import serializers

# this is DRF router for REST API viewsets
router = routers.DefaultRouter()

# register REST API endpoints with DRF router
router.register(r'restaurants', serializers.restaurantsViewSet, r"restaurants")


urlpatterns = [
  url(r'^$', views.index, name='index'),
  url(r'^listar/$', views.listar, name='listar'),
  url(r'^buscar/$', views.buscar, name='buscar'),
  url(r'^aniade/$', views.aniade, name='aniade'),
  url(r'^restaurante/(?P<id>[0-9]+)$', views.restaurante, name='restaurante'),
  # REST API root view (generated by DRF router)
  url(r'^api/', include(router.urls, namespace='api')),

]
